language: node_js

node_js:
  - "4"

addons:
  firefox: "47.0"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - firefox -v
  - npm install -g jpm@v1.1.0

script:
  - npm run lint
  - npm run jpm-travis
